POST http://localhost:8000/createdoctor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRhbWdhZDIzQGdtYWlsLmNvbSIsImlhdCI6MTc3NjQzNDQzNSwiZXhwIjoxNzc2NDM1MzM1fQ.FaaPgfAWFJGmqxAW4eyTxHOGu0jXIkt2XIAA7IQ0td8

{
    "name": "amgad",
    "email": "shing@gmail.com",
    "password": "123456789",
    "age": 21,
    "phone": "01157174086",
    "gender":"MALE",
    "department":"SURGERY",
    "specialization":"Brain"

}