POST http://localhost:8000/login
Content-Type: application/json

{    
    "email": "mohamedamgad23@gmail.com",
    "password": "123456789"
}

###
POST http://localhost:8000/reauth
Content-Type: application/json

{    
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRhbWdhZDIzQGdtYWlsLmNvbSIsImlhdCI6MTc3NDUzODgyMCwiZXhwIjoxNzc1MTQzNjIwfQ.SI0HPGNw8Of-8Ax5z8j6tN7-IBI6FZOdPskevnmKXDs"
}




#####
POST http://localhost:8000/signup
Content-Type: application/json

{
    "name": "amgad",
    "email": "mohamedamgad23@gmail.com",
    "password": "123456789",
    "age": 21,
    "phone": "01157174086" , 
    "ssn " : 123456789 
}